export const FETCH_TICKETS_REQUEST = "FETCH_TICKETS_REQUEST"; 
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS"; 
export const FETCH_TICKETS_FAILURE = "FETCH_TICKETS_FAILURE";
export const DELETE_TICKET_REQUEST = "DELETE_TICKET_REQUEST";
export const DELETE_TICKET_SUCCESS = "DELETE_TICKET_SUCCESS";
export const DELETE_TICKET_FAILURE = "DELETE_TICKET_FAILURE";

