export const FETCH_USERS_REQUEST =  "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS =  "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE =  "FETCH_USERS_FAILURE";
export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
